In [128]:
# import libraries
import numpy as np
from sklearn import linear_model
import pandas as pd
from sklearn.model_selection import train_test_split

In [261]:
# import dataset
dataset = pd.read_csv("./spiral/spiral.csv")
X, y = dataset.iloc[:, :-1], dataset.iloc[:, -1]
kwargs = dict(test_size=0.2, random_state=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, **kwargs)

clf = linear_model.SGDClassifier(max_iter=2000, tol=1e-3, alpha=0.00001)
# train classifier
clf.fit(X_train, y_train)

SGDClassifier(alpha=1e-05, average=False, class_weight=None,
       early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
       l1_ratio=0.15, learning_rate='optimal', loss='hinge', max_iter=2000,
       n_iter=None, n_iter_no_change=5, n_jobs=None, penalty='l2',
       power_t=0.5, random_state=None, shuffle=True, tol=0.001,
       validation_fraction=0.1, verbose=0, warm_start=False)

In [262]:


# predict
clf.predict(X_test)

predictions = clf.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, predictions))

print(classification_report(y_test, predictions))


[[ 5  0 14]
 [ 0 11  9]
 [ 0  0 21]]
              precision    recall  f1-score   support

           0       1.00      0.26      0.42        19
           1       1.00      0.55      0.71        20
           2       0.48      1.00      0.65        21

   micro avg       0.62      0.62      0.62        60
   macro avg       0.83      0.60      0.59        60
weighted avg       0.82      0.62      0.59        60



In [204]:
# import dataset
dataset = pd.read_csv("./spiral/spiral.csv")
X, y = dataset.iloc[:, :-1], dataset.iloc[:, -1]
kwargs = dict(test_size=0.2, random_state=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, **kwargs)

# MLP Classifier
from sklearn.neural_network import MLPClassifier
# Data Preprocessing - normalizing data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# Fit only to the training data
scaler.fit(X_train)

# Apply the transformations to the data:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
mlp = MLPClassifier(hidden_layer_sizes=(72,), alpha=0.01, tol=0.0001, max_iter=1200)
mlp.fit(X_train, y_train)



MLPClassifier(activation='relu', alpha=0.01, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(72,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [205]:
predictions = mlp.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, predictions))

print(classification_report(y_test, predictions))

[[18  0  1]
 [ 0 20  0]
 [ 0  0 21]]
              precision    recall  f1-score   support

           0       1.00      0.95      0.97        19
           1       1.00      1.00      1.00        20
           2       0.95      1.00      0.98        21

   micro avg       0.98      0.98      0.98        60
   macro avg       0.98      0.98      0.98        60
weighted avg       0.98      0.98      0.98        60

