In [27]:
from tensorflow.keras.datasets import mnist


#import matplotlib.pyplot as plt
(X_train_raw, y_train_raw), (X_test_raw, y_test_raw) = mnist.load_data()

# Preprocess input data
X_train = X_train_raw.reshape(X_train_raw.shape[0], 784)
X_test = X_test_raw.reshape(X_test_raw.shape[0], 784)

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
# Normalize values to 0...1
X_train /= 255
X_test /= 255

from tensorflow.keras.utils import to_categorical
# Preprocess class labels
# Convert labels to 10-dimensional one-hot vectors
Y_train = to_categorical(y_train_raw, 10)
Y_test = to_categorical(y_test_raw, 10)

#reshape data to fit model
# nr of images, shape, 1 = greyscale
#x_train = x_train.reshape(60000,28,28,1)
#x_test = x_test.reshape(10000,28,28,1)


# one-hot encode target column:
# a column will be created for each output category
# and a binary variable is inputted for each category
#y_train = to_categorical(y_train)
#y_test = to_categorical(y_test)
Y_train[0]



array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [21]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten

model = Sequential()

#model.add(Flatten())
model.add(Dense(10, input_dim=784, activation='softmax'))

model.compile(loss='categorical_crossentropy',
             optimizer='adam',
             metrics=['accuracy'])

%time model.fit(X_train, Y_train, batch_size=100, verbose=1, epochs=15)



Epoch 1/15
60000/60000 [==============================] - 3s 57us/step - loss: 0.6320 - acc: 0.8414
Epoch 2/15
60000/60000 [==============================] - 2s 38us/step - loss: 0.3473 - acc: 0.9061
Epoch 3/15
60000/60000 [==============================] - 2s 38us/step - loss: 0.3101 - acc: 0.9139
Epoch 4/15
60000/60000 [==============================] - 3s 45us/step - loss: 0.2930 - acc: 0.9185
Epoch 5/15
60000/60000 [==============================] - 3s 43us/step - loss: 0.2822 - acc: 0.9209
Epoch 6/15
60000/60000 [==============================] - 3s 42us/step - loss: 0.2751 - acc: 0.9235
Epoch 7/15
60000/60000 [==============================] - 2s 39us/step - loss: 0.2701 - acc: 0.9249
Epoch 8/15
60000/60000 [==============================] - 2s 39us/step - loss: 0.2654 - acc: 0.9255
Epoch 9/15
60000/60000 [==============================] - 2s 40us/step - loss: 0.2620 - acc: 0.9270
Epoch 10/15
60000/60000 [==============================] - 2s 41us/step - loss: 0.2592 - acc: 0.9286

In [26]:
score = model.evaluate(X_test, Y_test, verbose=0)
acc = score[1]
print(acc)
# Predict first 4 images in the test set
%time model.predict(X_test[:4])

0.9249
CPU times: user 79.5 ms, sys: 2.28 ms, total: 81.8 ms
Wall time: 81.7 ms


array([[1.6520698e-06, 1.5670380e-11, 7.3565052e-06, 6.7208037e-03,
        4.2414584e-07, 3.0470384e-05, 1.2516825e-10, 9.9284524e-01,
        1.8394132e-05, 3.7563519e-04],
       [1.9708593e-04, 3.8827457e-06, 9.8982596e-01, 1.9098507e-04,
        2.0536161e-14, 2.9519349e-03, 6.7752562e-03, 1.9253825e-17,
        5.4875542e-05, 6.1140790e-14],
       [1.1814665e-06, 9.8071623e-01, 1.1002055e-02, 2.6526919e-03,
        1.1194064e-04, 6.2253833e-04, 1.0633752e-03, 5.9646560e-04,
        2.9910810e-03, 2.4252223e-04],
       [9.9970019e-01, 3.6210288e-11, 6.8802343e-05, 5.6790091e-06,
        4.9063566e-08, 5.7560952e-05, 1.3034357e-04, 9.6827689e-06,
        1.0516442e-05, 1.7250657e-05]], dtype=float32)

In [24]:
# Compare with actual results
%time y_test[:4]

CPU times: user 9 µs, sys: 1 µs, total: 10 µs
Wall time: 16 µs


array([7, 2, 1, 0], dtype=uint8)