In [28]:
from tensorflow.keras.datasets import mnist
#import matplotlib.pyplot as plt
(x_train, y_train), (x_test, y_test) = mnist.load_data()

#reshape data to fit model
# nr of images, shape, 1 = greyscale
x_train = x_train.reshape(60000,28,28,1)
x_test = x_test.reshape(10000,28,28,1)

from tensorflow.keras.utils import to_categorical
# one-hot encode target column:
# a column will be created for each output category
# and a binary variable is inputted for each category
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)
y_train[0]



array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [29]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten

model = Sequential()

model.add(Flatten())
model.add(Dense(10, input_dim=784, activation='softmax'))

model.compile(loss='categorical_crossentropy',
             optimizer='adam',
             metrics=['accuracy'])

%time model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=15)



Train on 60000 samples, validate on 10000 samples
Epoch 1/15
60000/60000 [==============================] - 9s 142us/step - loss: 6.6078 - acc: 0.5852 - val_loss: 5.7701 - val_acc: 0.6389
Epoch 2/15
60000/60000 [==============================] - 8s 126us/step - loss: 5.6875 - acc: 0.6447 - val_loss: 5.4776 - val_acc: 0.6581
Epoch 3/15
60000/60000 [==============================] - 8s 128us/step - loss: 5.6944 - acc: 0.6450 - val_loss: 5.7206 - val_acc: 0.6431
Epoch 4/15
60000/60000 [==============================] - 8s 130us/step - loss: 5.5965 - acc: 0.6510 - val_loss: 5.4480 - val_acc: 0.6609
Epoch 5/15
60000/60000 [==============================] - 7s 123us/step - loss: 5.5632 - acc: 0.6534 - val_loss: 5.4244 - val_acc: 0.6625
Epoch 6/15
60000/60000 [==============================] - 8s 127us/step - loss: 5.5391 - acc: 0.6551 - val_loss: 5.7163 - val_acc: 0.6435
Epoch 7/15
60000/60000 [==============================] - 8s 135us/step - loss: 5.5237 - acc: 0.6561 - val_loss: 5.3378 - 

In [31]:
# Predict first 4 images in the test set
%time model.predict(x_test[:4])

CPU times: user 185 ms, sys: 7.52 ms, total: 193 ms
Wall time: 198 ms


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [32]:
# Compare with actual results
%time y_test[:4]

CPU times: user 12 µs, sys: 2 µs, total: 14 µs
Wall time: 21.9 µs


array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)